### ISSUE TITLE
Cannot read property 'Conversations' of undefined

### ISSUE THREAD

**Issue by DimitriosKaltzidis** [se02035/ViberMicrosoftBotFrameworkConnector#1]
I followed the steps and added my keys but when the viber bot receives a message and then uses the mbfBot.sendMessage(response.userProfile, message); it throws the error below. Why the _client is undefined ? 

[2017-07-17 14:43:49.585] [ERROR] Cannot read property 'Conversations' of undefined
  TypeError: Cannot read property 'Conversations' of undefined
      at MicrosoftBot._postActivity (/home/nowuser/src/node_modules/mbf-directline/microsoftBotConnector.js:77:25)
      at MicrosoftBot.sendMessage (/home/nowuser/src/node_modules/mbf-directline/microsoftBotConnector.js:147:14)
      at ViberBot.bot.on (/home/nowuser/src/src/index.js:69:12)
      at emitMany (events.js:151:20)
      at ViberBot.emit (events.js:223:7)
      at ViberBot._handleEventReceived (/home/nowuser/src/node_modules/viber-bot/lib/viber-bot.js:235:9)
      at Duplex.stream.on.data (/home/nowuser/src/node_modules/viber-bot/lib/viber-bot.js:220:9)
      at emitOne (events.js:115:13)
      at Duplex.emit (events.js:210:7)
      at addChunk (_stream_readable.js:252:12)

**Comment by alex-skiffin** [comment]
I have the same error. It manifests itself in the case when the conversation in the chat has already been opened. You must disable the chat dialog and enable it again. Or, somehow, modify the code to make createNewConversation run automatically if it is not been running before.
